Global:
  embedding_size: 100
  test_size: 0.2
  validate_size: 0.1

CNN:
  dropout_keep_prob: 0.5
  num_classes: 2
  num_filters: 128
  filter_sizes: 2,3,5  
  l2_reg_lambda: 0
  
RNN:
  num_classes: 2
  hidden_size: 128
  num_layers: 4
  l2_reg_lambda: 0
  cell_type: GRU
  bi-directional: True
  attention: True
  input_keep_prob: 0.5
  output_keep_prob: 0.5
  l2_reg_lambda: 0


  